import type { Metadata } from "next";
import { Orbit } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { detectConflictingPaths } from "next/dist/build/utils";
import StickyHeader from "@/components/StickyHeader";

export const metadata: Metadata = {
  title: "My Game Dev Blog",
  description: "Generated by create next app",
};

const orbitFont = Orbit({
  variable: "--font-orbit",
  subsets: ["latin"],
  weight: ["400"],
});

// const victorMono = Victor_Mono({
//   variable: "--font-victor-mono",
//   subsets: ["latin"],
//   display: "swap",
// });
// const workbench = Workbench({
//   variable: "--font-workbench",
//   subsets: ["latin"],
// });
// const sunFlowerFont = Sunflower({
//   variable: "--font-sunflower",
//   weight: ["300", "500", "700"],
// });
// const gowunBatangFont = Gowun_Batang({
//   variable: "--font-gowun-batang",
//   weight: ["400", "700"],
// });

// const cuteFont = Cute_Font({
//   weight: "400",
// });

// const notoSerifFont = Noto_Serif_KR({
//   weight: ["400", "700"],
// });

// const nanumGothicFont = Nanum_Gothic_Coding({
//   weight: ["400", "700"],
//   variable: "--font-nanum-gothic",
// });

// const dongleFont = Dongle({
//   weight: ["400", "700"],
//   variable: "--font-dongle",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footer = (
    <footer>
      <div className="border-t border-slate-500 mt-6 py-6 text-center text-slate-400">
        <h3>Developed by Gony</h3>
      </div>
    </footer>
  );

  return (
    <html lang="ko">
      <body className={`${orbitFont.className} `}>
        <div className="mx-auto max-w-3xl px-4">
          <StickyHeader />
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
