import type { Metadata } from "next";
import { Orbit, Victor_Mono } from "next/font/google";
import "../globals.css";
import StickyHeader from "@/components/StickyHeader";
import { i18n, type Locale } from "../../i18n-config";

export const metadata: Metadata = {
  title: "My Game Dev Blog",
  description: "Generated by create next app",
};

const orbitFont = Orbit({
  variable: "--font-orbit",
  subsets: ["latin"],
  weight: ["400"],
});

const victorMono = Victor_Mono({
  variable: "--font-victor-mono",
  subsets: ["latin"],
  display: "swap",
});
// const workbench = Workbench({
//   variable: "--font-workbench",
//   subsets: ["latin"],
// });
// const sunFlowerFont = Sunflower({
//   variable: "--font-sunflower",
//   weight: ["300", "500", "700"],
// });
// const gowunBatangFont = Gowun_Batang({
//   variable: "--font-gowun-batang",
//   weight: ["400", "700"],
// });

// const cuteFont = Cute_Font({
//   weight: "400",
// });

// const notoSerifFont = Noto_Serif_KR({
//   weight: ["400", "700"],
// });

// const nanumGothicFont = Nanum_Gothic_Coding({
//   weight: ["400", "700"],
//   variable: "--font-nanum-gothic",
// });

// const dongleFont = Dongle({
//   weight: ["400", "700"],
//   variable: "--font-dongle",
// });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = (await params) as { lang: Locale };
  const footer = (
    <footer>
      <div className="border-t border-white mt-6 py-6 text-center text-white">
        <h3>Developed by Gony</h3>
      </div>
    </footer>
  );

  return (
    <html lang={lang}>
      {/* <body className={(lang === 'ko') ?`${orbitFont.className} `:`${victorMono.className} `}> */}
      <body className={`${victorMono.className} `}>
        <div className="mx-auto max-w-3xl px-4">
          <StickyHeader />
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
